Gauss-Jordan:

In [1]:
import numpy as np

A=np.array([[0,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]], float)
v=np.array([[-4],[3],[9],[7]], float)


N = len(v)




#Check for diagonal zeros
def check(array):
    check = 1
    for i in range(len(array)):
        if(array[i,i]==0):
            check = 0
    return check


#Pivoting method
while(check(A)==0):
    for i in range(len(A)):
        for m in range(len(A)):
            A[[i,m]]=A[[m,i]]
            v[[i,m]]=v[[m,i]]

print(A)
print(v)


# Gaussian elimination                                                               


for m in range(N):

    # Divide by the diagonal element                                                  
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div

    # Now subtract from the lower rows                                                
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# Backsubstitution                                                                    
x = np.empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(x)

[[ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]
 [ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]]
[[ 9.]
 [ 7.]
 [-4.]
 [ 3.]]
[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


>Imagine you observe this planet with intensity of 1.25 ×10−12 (cgs units) at a wavelength of
λ= 870micron. What temperature does this correspond to in Kelvin? Your constants should
all be in cgs units, and your frequency in Hz. Do this using:
(a) The bisection method
(b) Newton-Raphson iteration

In [2]:
import math as math
import numpy as np

#in cgs units
c = 3e10
h = 6.6261e-27
lam = 0.087
v=c/lam
b=1.25e-12
k = 1.38e-16
m = 1e-2
x=2*h*v**3/c**2

def f(T):
    y = math.exp((h*v)/(k*T))-1
    z = x / y
    return b - z


#Part a: Bisection
print("Part A: Bisection Method")
a_i=15
b_i=60

for i in range(200):
    c_i= (a_i+b_i)/2
    if f(a_i)/f(c_i) < 0:
        b_i=c_i
    elif f(b_i)/f(c_i)<0:
        a_i=c_i
    if i == 199:
        print(c_i, f(c_i)) 
        break

#Part b: Newton-Raphson Method
print("Part B: Newton-Raphson Method")

for i in range(200):
    fp = ( f(a_i + m) - f(a_i - m))/(2*m)
    a_i = a_i - f(a_i)/fp
    if abs(f(a_i)) < m:
        print(a_i, f(a_i))
        break

Part A: Bisection Method
42.016071810134505 2.0194839173657902e-28
Part B: Newton-Raphson Method
42.01607181013451 -4.0389678347315804e-28
